# Generated by Django 5.2.17 on 2026-08-06 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=40, unique=True)),
                ('product_name', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=150)),
                ('product_category', models.CharField(max_length=100)),
                ('approval_number', models.CharField(max_length=80)),
                ('risk_class', models.CharField(max_length=20)),
                ('manufacturing_status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('manufacture_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('distribution_date', models.DateField(blank=True, null=True)),
                ('distribution_location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='DISTRIBUTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='devices.medicaldevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('medical_device', 'lot_number', 'serial_number'), name='unique_device_lot_serial')],
            },
        ),
    ]
