# Generated by Django 5.2.17 on 2026-08-06 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverse_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(default='FINAL', max_length=30)),
                ('decision', models.CharField(default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('adverse_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='adverse_events.adverseevent')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
