# Generated by Django 5.2.17 on 2026-08-09 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_display_name', models.CharField(max_length=200)),
                ('signer_role', models.CharField(max_length=30)),
                ('meaning', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('target_version', models.PositiveIntegerField(default=1)),
                ('canonical_data', models.JSONField()),
                ('data_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('current_hash', models.CharField(max_length=64, unique=True)),
                ('hash_algorithm', models.CharField(default='HMAC-SHA256', max_length=20)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('signed_at', models.DateTimeField()),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revocation', to='approvals.electronicsignature')),
            ],
        ),
    ]
