# Generated by Django 5.2.17 on 2026-08-06 00:48

import apps.adverse_events.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_location', models.CharField(max_length=150)),
                ('patient_age_group', models.CharField(blank=True, max_length=30)),
                ('patient_gender', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '치명적')], max_length=10)),
                ('reportability', models.CharField(choices=[('UNDETERMINED', '미결정'), ('NOT_REPORTABLE', '비보고'), ('REPORTABLE', '보고'), ('URGENT_REPORTABLE', '긴급보고')], default='UNDETERMINED', max_length=20)),
                ('event_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('RECEIVED', '접수'), ('UNDER_REVIEW', '검토'), ('INVESTIGATING', '조사'), ('CAPA_IN_PROGRESS', 'CAPA'), ('APPROVAL_PENDING', '승인대기'), ('REPORTING', '보고'), ('CLOSED', '종료'), ('REJECTED', '반려'), ('ON_HOLD', '보류')], default='RECEIVED', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('device_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='devices.devicelot')),
                ('medical_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='devices.medicaldevice')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', validators=[apps.adverse_events.models.validate_attachment])),
                ('file_type', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('adverse_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='adverse_events.adverseevent')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAnonymousInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_code', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('relevant_history', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adverse_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to='adverse_events.adverseevent')),
            ],
        ),
    ]
