# Generated by Django 5.2.17 on 2026-08-09 04:33

import apps.adverse_events.file_security
import apps.adverse_events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deletion_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='detected_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='retention_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='scan_engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='scan_status',
            field=models.CharField(choices=[('QUARANTINED', '격리'), ('CLEAN', '정상'), ('INFECTED', '감염'), ('SCAN_FAILED', '검사 실패')], default='QUARANTINED', max_length=20),
        ),
        migrations.AddField(
            model_name='attachment',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='storage_name',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=apps.adverse_events.file_security.PrivateMediaStorage(), upload_to='quarantine/%Y/%m/', validators=[apps.adverse_events.models.validate_attachment]),
        ),
    ]
