# Generated by Django 5.2.17 on 2026-08-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_events', '0002_attachment_deletion_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='scan_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='scan_error_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attachment',
            name='scan_next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
