# Generated by Django 5.2.17 on 2026-08-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditchainstate_auditlog_changed_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='key_id',
            field=models.CharField(default='legacy', max_length=100),
        ),
    ]
