# Generated by Django 5.2.17 on 2026-08-09 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_key_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditExportOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('PROCESSING', '처리 중'), ('RETRY', '재시도'), ('SENT', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='export_outbox', to='audit.auditlog')),
            ],
        ),
    ]
