# Generated by Django 5.2.17 on 2026-08-06 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='report_content',
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='capa_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='device_information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='document_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='event_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='investigation_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='patient_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='root_cause_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='submission_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryreport',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='report_number',
            field=models.CharField(blank=True, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='report_status',
            field=models.CharField(choices=[('DRAFT', '초안'), ('REVIEW_PENDING', '검토 대기'), ('APPROVED', '승인'), ('GENERATED', '문서 생성'), ('SUBMITTED', '제출 완료'), ('REJECTED', '반려')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='report_type',
            field=models.CharField(choices=[('INITIAL', '최초'), ('FOLLOW_UP', '추가'), ('FINAL', '최종'), ('INTERNAL', '내부')], default='INITIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='regulatoryreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
