# Generated by Django 5.2.17 on 2026-08-06 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverse_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_number', models.CharField(blank=True, max_length=22, unique=True)),
                ('capa_type', models.CharField(max_length=30)),
                ('issue_description', models.TextField()),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField()),
                ('planned_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('effectiveness_review', models.TextField(blank=True)),
                ('effectiveness_result', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adverse_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='adverse_events.adverseevent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
