# Generated by Django 5.2.17 on 2026-08-06 04:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='action_plan',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='capa',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='capa',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_capas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='planned_start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='capa',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_capas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capa',
            name='root_cause',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='capa',
            name='capa_type',
            field=models.CharField(choices=[('CORRECTIVE', '시정조치'), ('PREVENTIVE', '예방조치'), ('CORRECTIVE_PREVENTIVE', '시정·예방조치')], default='CORRECTIVE_PREVENTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='capa',
            name='corrective_action',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='effectiveness_result',
            field=models.CharField(choices=[('NOT_REVIEWED', '미평가'), ('EFFECTIVE', '효과적'), ('PARTIALLY_EFFECTIVE', '부분 효과'), ('INEFFECTIVE', '효과 없음')], default='NOT_REVIEWED', max_length=30),
        ),
        migrations.AlterField(
            model_name='capa',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_capas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capa',
            name='preventive_action',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='status',
            field=models.CharField(choices=[('DRAFT', '초안'), ('IN_PROGRESS', '진행 중'), ('REVIEW_PENDING', '검토 대기'), ('COMPLETED', '완료'), ('CLOSED', '종료'), ('CANCELLED', '취소')], default='DRAFT', max_length=30),
        ),
    ]
