# Generated by Django 5.2.17 on 2026-08-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0002_capa_action_plan_capa_actual_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', '초안'), ('REVIEW_PENDING', '검토 대기'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('NEEDS_REAPPROVAL', '재승인 필요')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='capa',
            name='approval_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
